services:
  app:
    build: .
    container_name: sghss-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sghss_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - sghss-network

  db:
    image: postgres:15-alpine
    container_name: sghss-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=sghss_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sghss-network
    healthcheck:
      test: ["CMD","pg_isready","-q","-U","postgres","-p","5432"]
      interval: 5s
      timeout: 1s
      retries: 2

  pgadmin:
    image: dpage/pgadmin4
    container_name: sghss-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - sghss-network

networks:
  sghss-network:
    driver: bridge

volumes:
  postgres_data: 